"""Merge deep-dive research data into existing knowledge/<mfg>/<family>.md files.

This does NOT regenerate the hand-authored knowledge files (canonical
description, scoring table, safeguards, approved language, sources). It only
inserts/updates two clearly-marked auto-generated blocks built from the
matching knowledge/<mfg>/research/<slug>.json produced by
scripts/tds_research_agent.py:

  - "Physical characteristics and product codes": every size/variant row from
    the manufacturer's own dimensions/packaging table (range_headers + range).
  - "Installation and clearances": the extracted install steps plus any
    stated clearance/safe-distance requirements.

Re-running is safe: each block is wrapped in an HTML comment marker pair and
fully replaced in place on the next run, so it stays in sync as research
files are refreshed. Everything outside the markers is left untouched.

Usage:
    python scripts/enrich_knowledge_docs.py --only Fletcher
    python scripts/enrich_knowledge_docs.py --family FLETCHER_PINK_BATTS_CEILING
    python scripts/enrich_knowledge_docs.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from tds_research_agent import research_path, slugify

VARIANTS_START = "<!-- AUTO:VARIANTS START (generated by scripts/enrich_knowledge_docs.py; do not hand-edit between markers) -->"
VARIANTS_END = "<!-- AUTO:VARIANTS END -->"
INSTALL_START = "<!-- AUTO:INSTALL START (generated by scripts/enrich_knowledge_docs.py; do not hand-edit between markers) -->"
INSTALL_END = "<!-- AUTO:INSTALL END -->"

# Section headings that anchor where each block is inserted if not already present.
VARIANTS_BEFORE_HEADING = "## Selection logic and metric discipline"
INSTALL_BEFORE_HEADING = "## Approved bot language"


def load_research(manufacturer_dir: str, family_name: str) -> dict | None:
    path = research_path(manufacturer_dir, slugify(family_name))
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None
    if data.get("status") != "ok" or not data.get("spec"):
        return None
    return data


def build_variants_block(research: dict) -> str | None:
    spec = research["spec"]
    headers = spec.get("range_headers") or []
    rows = [r for r in (spec.get("range") or []) if isinstance(r, dict)]
    if not headers or not rows:
        return None
    lines = [VARIANTS_START, "", "## Physical characteristics and product codes", ""]
    lines.append("| " + " | ".join(h.strip() for h in headers) + " |")
    lines.append("|" + " --- |" * len(headers))
    for row in rows:
        cells = [str(row.get(f"c{i}", "")).strip() for i in range(len(headers))]
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    lines.append(
        f"_Every size/product-code variant published in the current manufacturer datasheet "
        f"({research.get('datasheet_pdf_url', 'source pending')}); not a summary. Confirm current "
        f"availability and product codes before quoting._"
    )
    lines.append("")
    lines.append(VARIANTS_END)
    return "\n".join(lines)


def build_install_block(research: dict) -> str | None:
    spec = research["spec"]
    steps = [str(s).strip() for s in (spec.get("install") or []) if str(s).strip()]
    clearances = [str(c).strip() for c in (spec.get("clearances") or []) if str(c).strip()]
    limitations = [str(l).strip() for l in (spec.get("limitations") or []) if str(l).strip()]
    if not steps and not clearances:
        return None
    lines = [INSTALL_START, "", "## Installation and clearances", ""]
    if steps:
        lines.append(
            "Extracted from the manufacturer datasheet; the bot may share this context but must not issue "
            "project-specific installation instructions or override the human-reviewed install guide."
        )
        lines.append("")
        for i, step in enumerate(steps, 1):
            lines.append(f"{i}. {step.rstrip('.')}.")
        lines.append("")
    if clearances:
        lines.append("**Clearances and safe distances**")
        lines.append("")
        for item in clearances:
            lines.append(f"- {item.rstrip('.')}.")
        lines.append("")
    if limitations:
        lines.append("**Manufacturer-stated limitations**")
        lines.append("")
        for item in limitations:
            lines.append(f"- {item.rstrip('.')}.")
        lines.append("")
    lines.append(INSTALL_END)
    return "\n".join(lines)


def upsert_block(md: str, start_marker: str, end_marker: str, block: str, before_heading: str) -> str:
    pattern = re.compile(re.escape(start_marker) + r".*?" + re.escape(end_marker), re.S)
    if pattern.search(md):
        return pattern.sub(block, md)
    heading_pattern = re.compile(r"\n(?=" + re.escape(before_heading) + r"\s*\n)")
    if heading_pattern.search(md):
        return heading_pattern.sub("\n" + block + "\n\n", md, count=1)
    # anchor heading not found: append near the end, before the "## Sources" section if present
    sources_pattern = re.compile(r"\n(?=## Sources\s*\n)")
    if sources_pattern.search(md):
        return sources_pattern.sub("\n" + block + "\n\n", md, count=1)
    return md.rstrip("\n") + "\n\n" + block + "\n"


def enrich_file(md_path: Path, research: dict, dry_run: bool) -> bool:
    md = md_path.read_text(encoding="utf-8")
    original = md
    variants_block = build_variants_block(research)
    if variants_block:
        md = upsert_block(md, VARIANTS_START, VARIANTS_END, variants_block, VARIANTS_BEFORE_HEADING)
    install_block = build_install_block(research)
    if install_block:
        md = upsert_block(md, INSTALL_START, INSTALL_END, install_block, INSTALL_BEFORE_HEADING)
    if md == original:
        return False
    if not dry_run:
        md_path.write_text(md, encoding="utf-8")
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--only", help="one manufacturer directory name")
    parser.add_argument("--family", help="one family_id")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    changed = skipped = 0
    for path in sorted(ROOT.glob("knowledge/*/families.json")):
        manufacturer_dir = path.parent.name
        if args.only and manufacturer_dir.casefold() != args.only.casefold():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        for family in data["families"]:
            if args.family and family["family_id"] != args.family:
                continue
            knowledge_file = family.get("knowledge_file")
            if not knowledge_file:
                continue
            md_path = path.parent / knowledge_file
            if not md_path.exists():
                continue
            research = load_research(manufacturer_dir, family["name"])
            if not research:
                skipped += 1
                continue
            if enrich_file(md_path, research, args.dry_run):
                print(f"{'[dry-run] ' if args.dry_run else ''}enriched {md_path.relative_to(ROOT)}")
                changed += 1
            else:
                skipped += 1

    print(f"\nenriched: {changed}  skipped/no-change: {skipped}")


if __name__ == "__main__":
    main()
