"""Merge deep-dive research data into existing knowledge/<mfg>/<family>.md files.

This does NOT regenerate the hand-authored knowledge files (canonical
description, scoring table, safeguards, approved language, sources). It only
inserts/updates two clearly-marked auto-generated blocks built from the
matching knowledge/<mfg>/research/<slug>.json produced by
scripts/tds_research_agent.py:

  - "Physical characteristics and product codes": every size/variant row from
    the manufacturer's own dimensions/packaging table (range_headers + range).
  - "Installation and clearances": the extracted install steps plus any
    stated clearance/safe-distance requirements.

Re-running is safe: each block is wrapped in an HTML comment marker pair and
fully replaced in place on the next run, so it stays in sync as research
files are refreshed. Everything outside the markers is left untouched.

Usage:
    python scripts/enrich_knowledge_docs.py --only Fletcher
    python scripts/enrich_knowledge_docs.py --family FLETCHER_PINK_BATTS_CEILING
    python scripts/enrich_knowledge_docs.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from tds_research_agent import research_path, slugify

VARIANTS_START = "<!-- AUTO:VARIANTS START (generated by scripts/enrich_knowledge_docs.py; do not hand-edit between markers) -->"
VARIANTS_END = "<!-- AUTO:VARIANTS END -->"
INSTALL_START = "<!-- AUTO:INSTALL START (generated by scripts/enrich_knowledge_docs.py; do not hand-edit between markers) -->"
INSTALL_END = "<!-- AUTO:INSTALL END -->"

# Section headings that anchor where each block is inserted if not already present.
VARIANTS_BEFORE_HEADING = "## Selection logic and metric discipline"
INSTALL_BEFORE_HEADING = "## Approved bot language"


def load_research(manufacturer_dir: str, family_name: str, family_id: str = "") -> dict | None:
    research_dir = ROOT / "knowledge" / manufacturer_dir / "research"
    candidates = [research_path(manufacturer_dir, slugify(family_name))]
    names = {family_name, family_name.lower(), slugify(family_name), slugify(family_name).replace("-", "_")}
    names.update({family_id, family_id.lower(), slugify(family_id), slugify(family_id).replace("-", "_")})
    candidates.extend(research_dir / f"{name}.json" for name in names if name)
    seen: set[Path] = set()
    paths = [path for path in candidates if not (path in seen or seen.add(path))]
    paths.extend(path for path in sorted(research_dir.glob("*.json")) if path not in seen)
    for path in paths:
        if not path.exists():
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if data.get("status") != "ok" or not data.get("spec"):
            continue
        if data.get("family_id") == family_id or data.get("family_name", "").casefold() == family_name.casefold() or path in candidates[:len(names) + 1]:
            return data
    return None


def build_variants_block(research: dict) -> str | None:
    spec = research["spec"]
    headers = spec.get("range_headers") or []
    rows = [r for r in (spec.get("range") or []) if isinstance(r, dict)]
    technical = [item for item in (spec.get("technical") or []) if isinstance(item, dict) and item.get("property") and item.get("value")]
    if not headers or not rows:
        if not technical:
            source = research.get("datasheet_pdf_url") or "the current manufacturer source"
            return "\n".join([
                VARIANTS_START,
                "",
                "## Documented physical and technical properties",
                "",
                "_Variation data is pending a verified manufacturer range table or technical extraction. No dimensions, ratings or product combinations are inferred._",
                "",
                f"Source currently recorded: {source}",
                "",
                VARIANTS_END,
            ])
        headers = ["Published property", "Value", "Standard"]
        rows = [{"c0": item.get("property", ""), "c1": item.get("value", ""), "c2": item.get("standard", "")} for item in technical]
        title = "## Documented physical and technical properties"
        note = "_No manufacturer range table was available in the extracted source; this records each published technical property without inferring product combinations._"
    else:
        title = "## Physical characteristics and product codes"
        note = (
            f"_Every size/product-code variant published in the current manufacturer datasheet "
            f"({research.get('datasheet_pdf_url', 'source pending')}); not a summary. Confirm current "
            f"availability and product codes before quoting._"
        )
    lines = [VARIANTS_START, "", title, ""]
    lines.append("| " + " | ".join(h.strip() for h in headers) + " |")
    lines.append("|" + " --- |" * len(headers))
    for row in rows:
        cells = [str(row.get(f"c{i}", "")).strip() for i in range(len(headers))]
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    lines.append(note)
    lines.append("")
    lines.append(VARIANTS_END)
    return "\n".join(lines)


def build_install_block(research: dict) -> str | None:
    spec = research["spec"]
    steps = [str(s).strip() for s in (spec.get("install") or []) if str(s).strip()]
    clearances = [str(c).strip() for c in (spec.get("clearances") or []) if str(c).strip()]
    limitations = [str(l).strip() for l in (spec.get("limitations") or []) if str(l).strip()]
    if not steps and not clearances and not limitations:
        source = research.get("datasheet_pdf_url") or "the current manufacturer source"
        return "\n".join([
            INSTALL_START,
            "",
            "## Installation and clearances",
            "",
            "_Installation, clearance and limitation evidence is pending a verified manufacturer source. Do not infer project-specific installation instructions from this family file._",
            "",
            f"Source currently recorded: {source}",
            "",
            INSTALL_END,
        ])
    lines = [INSTALL_START, "", "## Installation and clearances", ""]
    if steps:
        lines.append(
            "Extracted from the manufacturer datasheet; the bot may share this context but must not issue "
            "project-specific installation instructions or override the human-reviewed install guide."
        )
        lines.append("")
        for i, step in enumerate(steps, 1):
            lines.append(f"{i}. {step.rstrip('.')}.")
        lines.append("")
    if clearances:
        lines.append("**Clearances and safe distances**")
        lines.append("")
        for item in clearances:
            lines.append(f"- {item.rstrip('.')}.")
        lines.append("")
    if limitations:
        lines.append("**Manufacturer-stated limitations**")
        lines.append("")
        for item in limitations:
            lines.append(f"- {item.rstrip('.')}.")
        lines.append("")
    lines.append(INSTALL_END)
    return "\n".join(lines)


def upsert_block(md: str, start_marker: str, end_marker: str, block: str, before_heading: str) -> str:
    pattern = re.compile(re.escape(start_marker) + r".*?" + re.escape(end_marker), re.S)
    if pattern.search(md):
        return pattern.sub(block, md)
    heading_pattern = re.compile(r"\n(?=" + re.escape(before_heading) + r"\s*\n)")
    if heading_pattern.search(md):
        return heading_pattern.sub("\n" + block + "\n\n", md, count=1)
    # anchor heading not found: append near the end, before the "## Sources" section if present
    sources_pattern = re.compile(r"\n(?=## Sources\s*\n)")
    if sources_pattern.search(md):
        return sources_pattern.sub("\n" + block + "\n\n", md, count=1)
    return md.rstrip("\n") + "\n\n" + block + "\n"


def enrich_file(md_path: Path, research: dict, dry_run: bool) -> bool:
    md = md_path.read_text(encoding="utf-8")
    original = md
    variants_block = build_variants_block(research)
    if variants_block:
        md = upsert_block(md, VARIANTS_START, VARIANTS_END, variants_block, VARIANTS_BEFORE_HEADING)
    install_block = build_install_block(research)
    if install_block:
        md = upsert_block(md, INSTALL_START, INSTALL_END, install_block, INSTALL_BEFORE_HEADING)
    if md == original:
        return False
    if not dry_run:
        md_path.write_text(md, encoding="utf-8")
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--only", help="one manufacturer directory name")
    parser.add_argument("--family", help="one family_id")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    changed = skipped = 0
    for path in sorted(ROOT.glob("knowledge/*/families.json")):
        manufacturer_dir = path.parent.name
        if args.only and manufacturer_dir.casefold() != args.only.casefold():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        for family in data["families"]:
            if args.family and family["family_id"] != args.family:
                continue
            knowledge_file = family.get("knowledge_file")
            if not knowledge_file:
                continue
            md_path = path.parent / knowledge_file
            if not md_path.exists():
                continue
            research = load_research(manufacturer_dir, family["name"], family["family_id"])
            if not research:
                research = {
                    "status": "research_pending",
                    "datasheet_pdf_url": family.get("source_url") or "",
                    "spec": {},
                }
            if enrich_file(md_path, research, args.dry_run):
                print(f"{'[dry-run] ' if args.dry_run else ''}enriched {md_path.relative_to(ROOT)}")
                changed += 1
            else:
                skipped += 1

    print(f"\nenriched: {changed}  skipped/no-change: {skipped}")


if __name__ == "__main__":
    main()
